// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://iuxotivoerhdhinhbysj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1eG90aXZvZXJoZGhpbmhieXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMzIxNTIsImV4cCI6MjA3MzkwODE1Mn0.BzaWtTzlKfFl3V7vyrZeYUsH0pZiIkx7_8-VkgBU5DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);